export const LANG_CN_NAME = 'cn';

export const LANG_CN_TRANS = {
    'HOME_TITLE': '您可以使用我们的预订应用程序预订表格',
    'BTN_BOOK_TABLE': '预订座位',
    'STEP1': '请选择日期',
    'STEP2': '请选择时间',
    'STEP3': '人数',
    'STEP5': '进行支付',
    'LUNCH': '午餐',
    'DINNER': '晚餐',
    'NEXT': '下一步',
    'NO_PEOPLE_HELP_TEXT': '对于超过12人的团体和功能，请进',
    'NO_PEOPLE_HELP_LINK': '行预订查询',
    'SIGN_UP_WE_CHAT': '微信注册',
    'SIGN_UP_PHONE': '电话号码注册',
    'IS_MEMBER': '已经是会员？',
    'LOGIN_HERE': '登录',
    'NAME': '姓名',
    'EMAIL': '邮件地址',
    'PHONE': '联系电话',
    'SPECIAL_REQUESTS': '特殊要求,需求或饮食限制?',
    'SMS_NOTIFICATION': '短信的代码，以验证电话号码发送',
    'VERIFICATION_CODE': '验证代码(通过短信发送)',
    'PROCEED_TO_PAYMENT': '继续付款',
    'PAYMENT_TITLE': '您将需要存入人民币',
    'PAYMENT_TITLE1': '每位客人保护您的桌子。',
    'GUESTS': '宾客',
    'RMB': 'RMB',
    'ALIPAY': '支付宝',
    'WECHAT': '微信支付',
    'PAYPAL': 'PayPal',
    'CARD': '在不支付订金的情况下预订',
    'MAKE_PAYMENT': '付款',
    'THANK_YOU': '谢谢',
    'BACK_TO_HOME': '回到主页',
    'CONFIRMATION_TEXT': '您在孔雀房预订确认，我们期待为您服务。',
    'TIME_UP_TITLE': '你的时间到了',
    'TIME_UP_TEXT': '对不起! 时间到。 请重新开始您的预订。',
    'ERROR_TITLE': '一些错误',
    'ERROR_TEXT': '哎呀！ 出了些问题。 请重新开始您的预订。',
    'NO_AVAILABILITY_TEXT': '对不起，在这个日期没有选定的时间和客人的可用性。 请更改您的查询或注册到等待列表。',
    'JOIN_WAITING_LIST': '加入等待名单t',
    'TERMS_TEXT': '我已阅读并接受预订',
    'TERMS_LINK': '条款&条件',
    'CONFIRM_WAITING_LIST': '确认等待列表',
    'WAITING_LIST_CONFIRMATION': '你加入了以上日期的等候名单，如果座位可用，我们会给你打电话。',
    'COPYRIGHT': '© 上海 FCC Food & Beverage Co. Ltd.',
    'LOGIN_WE_CHAT': '微信登录',
    'LOGIN_PHONE': '电话号码登录',
    'NOT_A_MEMBER': '非会员?',
    'SIGN_UP_LINK': '在这里注册',
    'LOGIN': '登录',
    'SIGNUP': '注册',
    'VERIFY_TO_LOGIN': '验证登录',
    'VERIFY_TO_SIGNUP': '验证注册',
    'LOGIN_ERROR_TITLE': '上面的电话号码已经链接到另一个帐户',
    'LOGIN_ERROR_DESC': '你想连接这个微信账号与这个电话号码账号 ?',
    'YES': '是',
    'NO': '否',
    'GOOD_MORNING': '你好',
    'MY_BOOKINGS': '我的预订',
    'CONNECT_WE_CHAT': '连接到微信',
    'LANGUAGE': '语言',
    'CONTACT_US': '联系我们',
    'LOG_OUT': '退出',
    'EDIT_PROFILE': '编辑个人资料',
    'SAVE': '保存',
    'UPCOMING': '预订',
    'PREVIOUS': '以前',
    'WELCOME_BACK': '欢迎回来',
    'MINUTE_UNIT': '分',
    'SECOND_UNIT': '秒',
    'SEATS_AVAILABLE': '座位可用'
};
