export const LANG_EN_NAME = 'en';

export const LANG_EN_TRANS = {
    'HOME_TITLE': 'You can reserve a table now using our booking app',
    'BTN_BOOK_TABLE': 'Book a table',
    'STEP1': 'Select Date',
    'STEP2': 'Select Time',
    'STEP3': 'No of Guests',
    'STEP5': 'Payment',
    'LUNCH': 'Lunch',
    'DINNER': 'Dinner',
    'NEXT': 'Next',
    'NO_PEOPLE_HELP_TEXT': 'For groups and functions larger than 12 people please make a',
    'NO_PEOPLE_HELP_LINK': 'booking enquiry',
    'SIGN_UP_WE_CHAT': 'Sign Up with WeChat',
    'SIGN_UP_PHONE': 'Sign Up with Phone Number',
    'IS_MEMBER': 'Already a Member?',
    'LOGIN_HERE': 'Login here',
    'NAME': 'Name',
    'EMAIL': 'Email',
    'PHONE': 'Phone Number',
    'SPECIAL_REQUESTS': 'Special Request',
    'SMS_NOTIFICATION': 'SMS sent with code to verify phone number',
    'VERIFICATION_CODE': 'Verification Code',
    'PROCEED_TO_PAYMENT': 'Proceed to Payment',
    'PAYMENT_TITLE': 'You will require to deposit RMB',
    'PAYMENT_TITLE1': 'per guest to secure your table.',
    'GUESTS': 'Guests',
    'RMB': 'RMB',
    'ALIPAY': 'Alipay',
    'WECHAT': 'WeChat Pay',
    'PAYPAL': 'PayPal (Foreign Cards)',
    'CARD': 'Book without Pay',
    'MAKE_PAYMENT': 'Make payment',
    'THANK_YOU': 'Thank you',
    'BACK_TO_HOME': 'Back to Home',
    'CONFIRMATION_TEXT': 'Your booking at The Peacock Room is confirm, and we look forward to serving you.',
    'TIME_UP_TITLE': 'Your Time Up',
    'TIME_UP_TEXT': 'Sorry! Time is over. Please start your booking all over again.',
    'ERROR_TITLE': 'Some Error',
    'ERROR_TEXT': 'Opps! Something went wrong. Please start your booking all over again.',
    'NO_AVAILABILITY_TEXT': 'Sorry, there is no availability for the selected time & guests on this date. Please change your inquiry or register to the waiting list.',
    'JOIN_WAITING_LIST': 'Join Waiting List',
    'TERMS_TEXT': 'I have read and accept the booking',
    'TERMS_LINK': 'terms & conditions',
    'CONFIRM_WAITING_LIST': 'Confirm Waiting List',
    'WAITING_LIST_CONFIRMATION': 'You joined waiting list for above date, if seat becomes available, we will give you a call.',
    'COPYRIGHT': '© Shanghai FCC Food & Beverage Co. Ltd.',
    'LOGIN_WE_CHAT': 'Login with WeChat',
    'LOGIN_PHONE': 'Login with Phone Number',
    'NOT_A_MEMBER': 'Not a member?',
    'SIGN_UP_LINK': 'Sign Up here',
    'LOGIN': 'Login',
    'SIGNUP': 'Sign Up',
    'VERIFY_TO_LOGIN': 'Verify to Login',
    'VERIFY_TO_SIGNUP': 'Verify to Sign Up',
    'LOGIN_ERROR_TITLE': 'Above phone number is already linked to another account',
    'LOGIN_ERROR_DESC': 'Would you like to connect this WeChat account with this phone number account ?',
    'YES': 'Yes',
    'NO': 'No',
    'GOOD_MORNING': 'Hi, welcome back',
    'MY_BOOKINGS': 'My Bookings',
    'CONNECT_WE_CHAT': 'Connected to WeChat',
    'LANGUAGE': 'Language',
    'CONTACT_US': 'Contact Us',
    'LOG_OUT': 'Log Out',
    'EDIT_PROFILE': 'Edit Profile',
    'SAVE': 'Save',
    'UPCOMING': 'Upcoming',
    'PREVIOUS': 'Previous',
    'WELCOME_BACK': 'Welcome Back',
    'MINUTE_UNIT': 'm',
    'SECOND_UNIT': 's',
    'SEATS_AVAILABLE': 'Seats Available'
};
